<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>6823d474-8aef-4d37-8c81-d0b3a2d986a6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Mortgage Default Prediction where
		default predicted is default predicted , 
		the probability is the probability ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
