<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Max Probability</name>
  <uuid>ee9eca70-8fb9-4fd4-b665-434c2c5c0bcc</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the maximum probability of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
