<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>fe202def-df73-416f-b996-13e9f014b7a3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to LTV ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
