<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>cc7a9d2b-9df8-4754-885c-6932f66edc8b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'Max affordable loan' * 'Credit score result';]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
