<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Convert Prediction to Boolean</name>
  <uuid>2eee23c8-2908-4970-8db4-16a2a09070ca</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the prediction of 'ML model invocation' is 0 
then
	set decision to false ; 
else
	set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
