<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Call Predicitve Model</name>
  <uuid>c928b734-d73a-4465-8e01-1673221c157f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[  set decision to the mortgage default predictor computed from
      age being the age of applicant , 
      credit score being the credit score of applicant , 
      dependants being the dependants of applicant , 
      emp length being the employment length of applicant , 
      income being the income of applicant , 
      loan being the loan of applicant , 
      missed payments being the missed payments of applicant , 
      property value being the property value of applicant , 
      term being the term of applicant ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
