<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Map output</name>
  <uuid>13b44f04-f9fc-4acd-8930-1ffe8f855279</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Surplus ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
