<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting 01</name>
  <uuid>6d3439d1-d957-4618-af75-47010f27d93d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Surplus ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
