<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Output</name>
  <uuid>02297ee2-34a6-4e45-8573-f65570e877ff</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Surplus ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
