<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Output Mapping</name>
  <uuid>02d8bb2b-d7d4-452e-8684-ed9b4b6f4ee8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Mortgage Default Prediction where
		default predicted is Prediction , 
		the probability is Probability ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
