<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Max Probability</name>
  <uuid>0959d461-5b0e-4201-9797-09224f6c1e4a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the maximum probability of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
