<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>4bd5ae51-4b77-4da5-92e8-5732d96e6158</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'Available deposit' + min ( 'Max loan based on financials' , 'Max loan based on property' ) ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
