<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Map Input Parameters</name>
  <uuid>10167e33-7eea-42dc-a6d6-b7fd9bfdd986</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the age is age , 
		the credit score is 'credit score' , 
		the dependants is dependants , 
		the emp length is 'emp length' , 
		the income is income , 
		the loan is loan , 
		the missed payments is 'missed payments' , 
		the property value is 'property value' , 
		the term is term ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
