<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Map Input Parameters</name>
  <uuid>e368a216-0944-400f-a39d-25af290276c4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the age is the age of applicant , 
		the credit score is the credit score of applicant , 
		the dependants is the dependants of applicant , 
		the emp length is the emp length of applicant , 
		the income is the income of applicant , 
		the loan is the loan of applicant , 
		the missed payments is the missed payments of applicant , 
		the property value is the property value of applicant , 
		the term is the term of applicant ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
