<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Otherwise Reject</name>
  <uuid>b589bd67-a75e-4417-97f0-9abeaa474b03</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Rejected ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
