<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>5130f138-4af9-4c43-8078-141e19665c2b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'Gross yearly income' * 4.5 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
