<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get prediction</name>
  <uuid>d7447c36-a1c4-4433-b1bc-86fc671ae828</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[   set decision to the mortgage default predictor computed from
      applicant being 'Update Applicant Score' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
