<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Determine Default Predicted</name>
  <uuid>73578c5c-7416-46b5-9af2-828f03bb664f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the prediction of 'ML model invocation' is 0
then
	set decision to false ; 
else 
	set decision to true ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
