<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Map output</name>
  <uuid>3d8bc844-521d-41e4-bdcc-5d17f50f495d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'prediction result' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
